2022-03-29 00:16:26,162 INFO    Thread-19 :16958 [wandb_setup.py:_flush():75] Loading settings from /Users/15leer1/.config/wandb/settings
2022-03-29 00:16:26,162 INFO    Thread-19 :16958 [wandb_setup.py:_flush():75] Loading settings from wandb/settings
2022-03-29 00:16:26,162 INFO    Thread-19 :16958 [wandb_setup.py:_flush():75] Loading settings from environment variables: {'project': 'trash-ai', 'entity': 'trash-ai', 'root_dir': '/Users/15leer1/Documents/GitHub/Garbage-Classification-App', 'run_id': 'e1mxv59z', 'sweep_param_path': '/Users/15leer1/Documents/GitHub/Garbage-Classification-App/wandb/sweep-sckucduo/config-e1mxv59z.yaml', 'sweep_id': 'sckucduo'}
2022-03-29 00:16:26,162 INFO    Thread-19 :16958 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'sweeps.py', 'program': '/Users/15leer1/Documents/GitHub/Garbage-Classification-App/sweeps.py'}
2022-03-29 00:16:26,162 INFO    Thread-19 :16958 [wandb_init.py:_log_setup():405] Logging user logs to /Users/15leer1/Documents/GitHub/Garbage-Classification-App/wandb/run-20220329_001626-e1mxv59z/logs/debug.log
2022-03-29 00:16:26,162 INFO    Thread-19 :16958 [wandb_init.py:_log_setup():406] Logging internal logs to /Users/15leer1/Documents/GitHub/Garbage-Classification-App/wandb/run-20220329_001626-e1mxv59z/logs/debug-internal.log
2022-03-29 00:16:26,163 INFO    Thread-19 :16958 [wandb_init.py:init():439] calling init triggers
2022-03-29 00:16:26,163 INFO    Thread-19 :16958 [wandb_init.py:init():442] wandb.init called with sweep_config: {'batch_size': 16, 'lr': 0.008122773397448057, 'model': 'efficientnet_b4'}
config: {}
2022-03-29 00:16:26,163 INFO    Thread-19 :16958 [wandb_init.py:init():492] starting backend
2022-03-29 00:16:26,163 INFO    Thread-19 :16958 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2022-03-29 00:16:26,168 INFO    Thread-19 :16958 [backend.py:ensure_launched():219] starting backend process...
2022-03-29 00:16:26,174 INFO    Thread-19 :16958 [backend.py:ensure_launched():224] started backend process with pid: 17006
2022-03-29 00:16:26,176 INFO    Thread-19 :16958 [wandb_init.py:init():501] backend started and connected
2022-03-29 00:16:26,183 INFO    Thread-19 :16958 [wandb_run.py:_config_callback():992] config_cb None None {'batch_size': 16, 'lr': 0.008122773397448057, 'model': 'efficientnet_b4'}
2022-03-29 00:16:26,186 INFO    Thread-19 :16958 [wandb_init.py:init():565] updated telemetry
2022-03-29 00:16:26,201 INFO    Thread-19 :16958 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-29 00:16:26,726 INFO    Thread-19 :16958 [wandb_run.py:_on_init():1759] communicating current version
2022-03-29 00:16:26,811 INFO    Thread-19 :16958 [wandb_run.py:_on_init():1763] got version response 
2022-03-29 00:16:26,811 INFO    Thread-19 :16958 [wandb_init.py:init():625] starting run threads in backend
2022-03-29 00:16:26,917 INFO    Thread-19 :16958 [wandb_run.py:_console_start():1733] atexit reg
2022-03-29 00:16:26,917 INFO    Thread-19 :16958 [wandb_run.py:_redirect():1606] redirect: SettingsConsole.REDIRECT
2022-03-29 00:16:26,917 INFO    Thread-19 :16958 [wandb_run.py:_redirect():1611] Redirecting console.
2022-03-29 00:16:26,918 ERROR   Thread-19 :16958 [wandb_run.py:_redirect():1670] Failed to redirect.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1663, in _redirect
    out_redir.install()
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/opt/homebrew/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/signal.py", line 56, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
2022-03-29 00:16:26,918 INFO    Thread-19 :16958 [wandb_init.py:init():664] run started, returning control to user process
2022-03-29 00:16:27,533 INFO    Thread-19 :16958 [wandb_run.py:finish():1539] finishing run trash-ai/trash-ai/e1mxv59z
2022-03-29 00:16:27,533 INFO    Thread-19 :16958 [wandb_run.py:_atexit_cleanup():1702] got exitcode: 1
2022-03-29 00:16:27,534 INFO    Thread-19 :16958 [wandb_run.py:_restore():1674] restore
2022-03-29 00:16:27,536 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 812
  total_bytes: 812
}

2022-03-29 00:16:28,177 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 812
  total_bytes: 812
}

2022-03-29 00:16:28,307 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 812
  total_bytes: 812
}

2022-03-29 00:16:28,746 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 812
  total_bytes: 2608
}

2022-03-29 00:16:28,854 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 812
  total_bytes: 2608
}

2022-03-29 00:16:28,961 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2608
  total_bytes: 2608
}

2022-03-29 00:16:29,072 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2608
  total_bytes: 2608
}

2022-03-29 00:16:29,174 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2608
  total_bytes: 2608
}

2022-03-29 00:16:29,285 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2608
  total_bytes: 2608
}

2022-03-29 00:16:29,468 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2608
  total_bytes: 2608
}

2022-03-29 00:16:29,918 INFO    Thread-19 :16958 [wandb_run.py:_on_finish():1831] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 2608
  total_bytes: 2608
}
local_info {
}

2022-03-29 00:16:31,025 INFO    Thread-19 :16958 [wandb_run.py:_footer_history_summary_info():2865] rendering history
2022-03-29 00:16:31,026 INFO    Thread-19 :16958 [wandb_run.py:_footer_history_summary_info():2894] rendering summary
2022-03-29 00:16:31,026 INFO    Thread-19 :16958 [wandb_run.py:_footer_sync_info():2822] logging synced files
